init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "6.9"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn && yarn

build: off

test_script:
  - node --version
  - npm --version
  - npm run build && npm run test

version: "{build}"